# Configuration for cargo-deny
# Supply chain security and dependency management

[advisories]
# Security vulnerability database checking
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
ignore = [
    # Add specific advisory IDs to ignore (with justification)
    # "RUSTSEC-2020-0001",  # Example: False positive for ZK use case
]

[licenses]
# License compatibility checking
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

# Cryptographic libraries exemptions
[[licenses.exceptions]]
allow = ["Apache-2.0", "MIT"]
name = "ring"  # Cryptographic library

[bans]
# Dependency bans and duplicate detection
multiple-versions = "warn"
wildcards = "allow"  # Needed for crypto development
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

# Prevent problematic crates
deny = [
    # Network request libraries (ZK proofs should be self-contained)
    { name = "reqwest", reason = "Unexpected network dependency" },
    { name = "ureq", reason = "Unexpected network dependency" },
    
    # Insecure crypto (ensure using ark-crypto-primitives)
    { name = "md5", reason = "Use SHA3 or BLAKE3 instead" },
    { name = "sha1", reason = "Use SHA3 or BLAKE3 instead" },
]

# Allow duplicate versions for these (different major versions)
skip = [
    { name = "syn" },       # Proc macro ecosystem
    { name = "windows-sys" }, # Windows dependencies
]

# Skip tree root analysis
skip-tree = [
    { name = "ark-std" },   # ZK cryptography ecosystem
]

[sources]
# Source code origin validation
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/arkworks-rs/",  # Trusted ZK cryptography org
]