name: Feature Request
description: Suggest a new feature or enhancement for ZKP Dataset Ledger
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees:
  - danieleschmidt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea clearly.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a specific use case?
      placeholder: Describe the problem or limitation you're facing
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: What would you like to happen?
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions you've considered
      
  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of the project does this feature relate to?
      options:
        - Core Cryptography (ZK Proofs)
        - Dataset Processing
        - CLI Interface
        - Storage Backend
        - Documentation
        - Performance
        - Security
        - API/Integration
        - Other
    validations:
      required: true
      
  - type: textarea
    id: example
    attributes:
      label: Usage Example
      description: Provide a concrete example of how this feature would be used
      placeholder: |
        ```bash
        zkp-ledger new-feature --example
        ```
        or
        ```rust
        ledger.new_method(param)?
        ```
      render: markdown
      
  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide use case examples