version: '3.8'

services:
  zkp-ledger:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: zkp-ledger
    restart: unless-stopped
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Environment configuration
    environment:
      - RUST_LOG=info
      - LEDGER_STORAGE_PATH=/data/ledger.json
      - LEDGER_BACKUP_PATH=/data/backups
      - LEDGER_MAX_FILE_SIZE=10737418240  # 10GB
      - LEDGER_BACKUP_INTERVAL=3600       # 1 hour
    
    # Persistent data storage
    volumes:
      - ledger_data:/data
      - ledger_backups:/data/backups
      - ./datasets:/datasets:ro  # Read-only dataset access
    
    # Network configuration
    networks:
      - zkp_network
    
    # Health monitoring
    healthcheck:
      test: ["CMD", "zkp-ledger", "stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: false  # Need write access for ledger storage
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Monitoring with Prometheus metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: zkp-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - zkp_network
    profiles: ["monitoring"]

  # Optional: Log aggregation with Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: zkp-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - zkp_network
    profiles: ["monitoring"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123

volumes:
  ledger_data:
    driver: local
  ledger_backups:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  zkp_network:
    driver: bridge
    enable_ipv6: false