# Prometheus configuration for ZKP Dataset Ledger monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'zkp-ledger'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configuration
scrape_configs:
  # ZKP Dataset Ledger main application
  - job_name: 'zkp-ledger'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9090

  # PostgreSQL metrics (if using postgres backend)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # RocksDB metrics (if using rocksdb backend)  
  - job_name: 'rocksdb'
    static_configs:
      - targets: ['localhost:9091']
    scrape_interval: 30s
    metrics_path: '/rocksdb-metrics'

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # Container metrics
  - job_name: 'cadvisor'
    static_configs: 
      - targets: ['localhost:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"
      path_prefix: /
      scheme: http
      timeout: 10s
      api_version: v2

# Remote write for long-term storage (optional)
remote_write:
  - url: "https://prometheus-remote-write-endpoint/api/v1/write"
    remote_timeout: 30s
    queue_config:
      capacity: 2500
      max_shards: 200
      min_shards: 1
      max_samples_per_send: 500
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms