[package]
name = "zkp-ledger-basic-example"
version = "0.1.0"
edition = "2021"

[dependencies]
zkp-dataset-ledger = { path = "../.." }
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = "0.3"